outputDir: "dev.generated"
services:
  gateway:
    base: "gateway.yaml"
    output: "gateway.yaml"
  user-service:
    base: "user_service.yaml"
    output: "user_service.yaml"
  problem-service:
    base: "problem_service.yaml"
    output: "problem_service.yaml"
  submit-service:
    base: "submit_service.yaml"
    output: "submit_service.yaml"
  judge-service:
    base: "judge_service.yaml"
    output: "judge_service.yaml"
