server:
  addr: "0.0.0.0:8083"
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "60s"

grpc:
  addr: "0.0.0.0:9093"

logger:
  level: "info"
  format: "json"
  outputPath: "stdout"
  errorPath: "stderr"
